# Generated by Django 5.1.6 on 2025-05-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('category', models.ManyToManyField(to='Category.category')),
            ],
        ),
    ]
