# Generated by Django 5.1.6 on 2025-05-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
